const mongoose = require('mongoose');
const recipeTemplate = new mongoose.Schema({
    user:{
        type:mongoose.Schema.Types.ObjectId,
        ref:'users'
    },
    category:{
        type:String,
        required:true
    },
    cuisine:{
        type:String,
        required:true
    },
    title:{
        type:String,
        required:true,
        unique:true
    },
    image:{
        type:String,
        required:true
    },
    description:{
        type:String,
        required:true
    },
    ingredients:{
        type:[String],
        required:true
    },
    steps:{
        type:[String],
        required:true
    },
    difficulty:{
        type:String,
        required:true
    },
    yeild:{
        type:String,
        required:true
    },
    numOfPeople:{
        type:String,
        required:true
    },
    times:{
        type:String,
        required:true
    },
    numOfLike:{
        type:Number,
        default:0
    },
    numOfFavourited:{
        type:Number,
        default:0
    },
    date:{
        type:Date,
        default:Date.now
    },
})

module.exports = mongoose.model('recipes',recipeTemplate);